@startuml Animal
class Animal {
    + name: String
    + eat(): void
    + sleep(): void
}

class Dog {
    + bark(): void
}

class Cat {
    + meow(): void
}

Dog --|> Animal
Cat --|> Animal

@enduml
